### PR TITLE
Syncing with new liboqs algorithm list.

### PR DESCRIPTION
**Pull request by xvzcf**

### CODE REVIEW

**Review by baentsch — APPROVED** [review]
LGTM. There doesn't seem to be any interest for documentation of previous algorithm variants in openssh, right? Linking to https://github.com/open-quantum-safe/oqs-provider/issues/163 to get agreement on this.

**Comment by csosto-pk** [comment]
Thx. Waiting for this to get merged, so I test again.

**Comment by dstebila** [comment]
I don't think there's a need to archive old method names.

We do want to make sure we are using new method names for incompatible variants due to algorithm updates. The SPHINCS+ updates are compatibility breaking, but the name change also leads to new method names, so we're good there.

However this does raise the question if we should fix the earlier oversight (as noted in discussion in https://github.com/open-quantum-safe/openssh/issues/134) of not following SSH conventions for non-standardized names.  In particular, should we add an `@openquantumsafe.org` suffix to any new names that we're introducing here?

**Comment by csosto-pk** [comment]
> However this does raise the question if we should fix the earlier oversight (as noted in discussion in https://github.com/open-quantum-safe/openssh/issues/134) of not following SSH conventions for non-standardized names. In particular, should we add an @openquantumsafe.org suffix to any new names that we're introducing here?

Imo, it is not worth the pain. You can follow the nomenclature when you make compatibility breaking changes and have to update the SSH method name. No need to update everything that you have been using for so long.

**Comment by baentsch** [comment]
Our convention is that the author merges PRs once approved, except stated otherwise, right? So why has this not been merged? Who else needs to approve? This is holding up https://github.com/open-quantum-safe/oqs-demos/pull/201 and with it, doing downstream testing of the release of `liboqs` (as well as @csosto-pk and anyone else interested in using oqs-openssh with the latest `liboqs`).

**Pull request merged**
