### PR TITLE
Apply upstream refactor to sshkey.c

### PR DESCRIPTION
**Pull request by geedo0**
In PR #159 we resolved a massive merge conflict in `sshkey.c` by simply taking the upstream version and removing all PQ SSH key support from the trunk. This broke the build/tests and obviously the ability to use PQ SSH keys. This PR restores PQ SSH key support for "pure" PQ algorithms. A follow-up PR will bring back support for hybrid-PQ. This was done to break up the PRs and do things more incrementally.

At a high-level, there was a major refactor of `sshkey` upstream which moved algorithm implementations to an OOP abstraction via the `sshkey_impl` struct. This allowed them to get rid of all the switch statements, encapsulate algorithm specific code, and standardize on a single factory method to get the right implementation. Some other minor things like the function signatures for sign/verify were updated to accept new optional arguments.

Getting OQS over to this new system was a matter of defining these `sshkey_impl` structs and factoring out the relevant OQS bits to the proper functions. This involved a number of changes/renames/deletions to the templates. I also performed a 3-way merge to pull-in changes that weren't directly impacted by the refactor.

There is no support for hybrid SSH Key support for now. This is to make sure that the baseline refactor is in a good shape before committing to a certain path. To support hybrid, I propose implementing generic hybrid versions of these classes. The only tricky thing is figuring out how to expose the RSA/EC implementations to the `ssh-oqs` file (probably declaring externs?). I considered doing this "on the outside", but that seems to go against what the refactor aimed to do and adds a lot more complexity to the sshkey source than seems necessary.

What's working now?
- `build_openssh.sh` now compiles and installs successfully 🎉
- CI passes as long as tests for the missing hybrid SSH key support is skipped.
- Upstream OpenSSH CI and `make tests` target fail, but these are to be pre-existing defects.

Related to Issue #135

### CODE REVIEW

**Review by dstebila — APPROVED** [review]

**Comment by geedo0** [comment]
Can we merge the PR (I don't have permissions to do this) or are we waiting on more feedback or testing? Squash merge is fine/preferred here since this isn't an upstream merge. I have a number of other changes that depend on this one and can't get the PR's submitted until this one is merged.

**Comment by dstebila** [comment]
> Can we merge the PR (I don't have permissions to do this) or are we waiting on more feedback or testing? Squash merge is fine/preferred here since this isn't an upstream merge. I have a number of other changes that depend on this one and can't get the PR's submitted until this one is merged.

Was just hoping to get one more set of eyes on this before merging.

**Review by baentsch — APPROVED** [review]
I'd suggest merging as-is even though there are rough edges (#ifdef close comments not merging starts, say)--with the understanding this work will move to functional equivalence with the 8.x variant--as discussed, ideally with some interop test between old and new such as to make acceptance of this substantial piece of work reasonably doable without diving into all details.

**Comment by geedo0** [comment]
> I'd suggest merging as-is even though there are rough edges (#ifdef close comments not merging starts, say)--with the understanding this work will move to functional equivalence with the 8.x variant--as discussed, ideally with some interop test between old and new such as to make acceptance of this substantial piece of work reasonably doable without diving into all details.

My plan is to present more in depth validation as this gets closer to done (e.g. the next PR on hybrid SSH Keys is a better checkpoint for that). I wanted to avoid some hassle on temporarily working around things when we can tell a much cleaner story around validation with a complete implementation. Hope that's alright and makes sense.

**Pull request merged**
