### PR TITLE
Add libOQS/NewHope support to openssh-portable

### PR DESCRIPTION
**Pull request by truth-quark**
Added NewHope algorithm so the liboqs master and openssh-portable have the same algorithms.

Manual client/server testing on an Ubuntu 18.04.1 worked without problems with the 4 variants of the NewHope algorithm.

### CODE REVIEW

**Comment by himsen** [comment]
Did you run:
$make tests

**Comment by truth-quark** [comment]
> Did you run:
> $make tests

Yes, as far as I know the tests are broken and didn't complete, even from a fresh checkout of the oqs-master branch.

**Comment by himsen** [comment]
That should not be the case. Let me have a look. Can you attach an output of a run?

**Comment by himsen** [comment]
I tried both the build in tests and running manually with hybrid key exchange using the default OQS algorithm, not on this PR though. Both failed.

What sort of 'manual' tests did you do?

There seems to be a more substantial problem here. My bet is that there is some memory corruption happening at some point.

**Comment by truth-quark** [comment]
> I tried both the build in tests and running manually with hybrid key exchange using the default OQS algorithm, not on this PR though. Both failed.
> 
> What sort of 'manual' tests did you do?

My manual tests were to run the client/server demo, see 'Running' here:
https://github.com/open-quantum-safe/openssh-portable/blob/OQS-master/README.md

Doing a 'make tests' fails on my Ubuntu VMs due to a problem with dynamic linking or LD_LIBRARY_PATH. I'll debug that before trying to recreate the bug you've raised.

**Review by dstebila — APPROVED** [review]

**Pull request merged**
