### PR TITLE
Adds hybrid auth.

### PR DESCRIPTION
**Pull request by christianpaquin**
This PR adds hybrid auth.

Not ready for merge yet, first need to:
- Test all hybrid cases (and update integration tests)

### CODE REVIEW

**Comment by christianpaquin** [comment]
@dstebila; I tested the all the hybrid schemes locally and it works for me. I've updated the testing script (see draft [PR29](https://github.com/open-quantum-safe/testing/pull/29) of that project); I have yet to install the toolset on my dev box, so I didn't run it locally. The CircleCI fails on that PR, but I think you mentionned there were open issues for that project. Anyway, you are welcome to try to run the script manually, or we can queue this until the tests are ready.

**Comment by dstebila** [comment]
Thanks Christian. I've taken a look at the CircleCI builds.  Some failures are expected, but some are new based on this PR.

In this build (https://circleci.com/gh/open-quantum-safe/testing/282), the SSH install step is failing because it says some key types are not recognized during the step where it sets up the default keys for the SSH server.

In this build (https://circleci.com/gh/open-quantum-safe/testing/291), which is where PQ auth shold be disabled, there are compilation errors, probably because certain things are not ifdef'd out correctly.

**Comment by christianpaquin** [comment]
OK, @dstebila, I'll take a look at the errors when running `make install` and when disabling PQ auth.

**Comment by christianpaquin** [comment]
@dstebila, you can give it another try...

**Comment by dstebila** [comment]
Still getting a failure that I don't expect.

https://circleci.com/gh/open-quantum-safe/testing/300
https://circleci.com/gh/open-quantum-safe/testing/306

```
sshkey.c: In function 'sshkey_verify':
sshkey.c:2681:3: error: a label can only be part of a statement and a declaration is not a statement
   int index = 0;
   ^
```

**Comment by christianpaquin** [comment]
Oh, this is code I just changed to fix an issue. It is problematic when hybrid is enabled (and the last case I tried was PQ-only). We have a lot of enable/disable KEX/auth cases! Anyway, I think I fixed it correctly this time. I need to install CircleCI to test locally too...

**Review by dstebila — APPROVED** [review]

**Pull request merged**
