### PR TITLE
Update method names in kex.h

### PR DESCRIPTION
**Pull request by csosto-pk**
[PR# 136](https://github.com/csosto-pk/opensshpq-136/pull/1) breaks backwards compatibility for PQ-hybrid key exchange methods. As agreed in [Issue #136](https://github.com/open-quantum-safe/openssh/issues/136) we ought to update the names. 

This PR includes two commits
- [Commit #16c98d1](https://github.com/open-quantum-safe/openssh/pull/138/commits/16c98d1f34b7d38d2fa792e520e16a5913acf65e) updates just the three method names which are in [the draft](https://github.com/csosto-pk/pq-ssh/blob/master/draft-kampanakis-ssh-pq-ke.txt). If you want to reject the second commit in this PR, feel free to just take this one.
- [Commit #5fd6eab](https://github.com/open-quantum-safe/openssh/pull/138/commits/5fd6eabe5614e5ba5f26a572b73bbcb6c41b9dcb) updates the rest of the PQ-hybrid key exchange method names. 
  - It does not use `-d00` as these are not in the draft.
  - It uses `-r2` for Frodo since it was not picker in Round 3. For the rest it uses `-r3`.

### CODE REVIEW

**Comment by dstebila** [comment]
Updated to use our templating method to populate those files, in kex.h and elsewhere.

**Comment by dstebila** [comment]
Are we okay to merge without the AppVeyor builds passing?

**Comment by baentsch** [comment]
> Are we okay to merge without the AppVeyor builds passing?

Personally I don't consider this appropriate: Either we disable tests (as part of a PR) that we now consider irrelevant (e.g., because we don't want to support Windows any more) or we stick to the same (test) standard we applied before. In either case, CI should be "green".

**Comment by christianpaquin** [comment]
We can merge this first, and then update libssh (see [discussion here](https://github.com/open-quantum-safe/libssh/issues/18#issuecomment-1487502973)). Can you rebase on top of #140 to fix the failing CI?

**Review by christianpaquin — APPROVED** [review]
Thanks Panos

**Pull request merged**
