### PR TITLE
Fixing encoding issue 136

### LINKED ISSUE #136: PQ-hybrid key exchange encodings
Hi, 

As we are interop testing we found an issue in how OQS OpenSSH encodes the exchanged keys.

The way it works today in OQS OpenSSH, the shared secret is `K = HASH((PQ shared key) || (ECDH shared key))`
- The ```PQ shared key``` is encoded as raw data (`byte` in the SSH RFC https://www.rfc-editor.org/rfc/rfc4251#section-5 ). 
- The ```ECDH shared key``` is encoded as ```mpint``` as per the SSH RFC https://www.rfc-editor.org/rfc/rfc4251#section-5 . That is probably because that it was done previously as per RFC4253 and because the exchanged ECDH shared key is a big integer and `K` ended up being `mpint`. 
- `K = HASH((PQ shared key) || (ECDH shared key))` is used as a `byte` array for deriving encryption keys for SSH https://github.com/open-quantum-safe/openssh/blob/92c59cf2f25fb32b21ce8d7b11a8af246ea17062/kexoqsecdh.c#L94 

The PQ SSH draft is currently a little ambiguous on this, and I will update it to be more prescriptive, but we want to make a suggestion here to make sure we are all implementers on the same page: 

Both ```PQ shared key``` and ```ECDH shared key``` would rather be a simple `byte` array padded to the nearest byte boundary. Previously `mpint` worked because ```ECDH shared key``` was going directly into `K`, but that is not the case any more. ```PQ shared key``` and ```ECDH shared key``` go into a hash, so they ought to be raw data, fixed-length, simple `byte` array padded to the nearest byte boundary. Using `mpint` for one shared key and raw data for the other is inconsistent and `mpint` adds some predictability into the content of the hash input buffer. 

Btw, that is what OpenSSH does with its X25519+SNTRU PQ-hybrid key exchange method. 

@dstebila , @baentsch , @christianpaquin , what do you think?

### PR DESCRIPTION
**Pull request by csosto-pk**
Fixing a interop issue with how the ECDH shared secret is represented before passed as input into the SSH KDF. It should no longer be an `mpint`, it is should be raw data / `byte` array. Btw, that is what OpenSSH does with its X25519+SNTRU PQ-hybrid key exchange method. 

More details in [issue #136](https://github.com/open-quantum-safe/openssh/issues/136)

Patch courtesy of @geedo0 .

Fixes #136

### CODE REVIEW

**Comment by dstebila** [comment]
The AppVeyor build is failing (https://ci.appveyor.com/project/dstebila/openssh/builds/46446128) but this seems to be unrelated to the changes in this PR.  @christianpaquin any ideas?

**Comment by christianpaquin** [comment]
Looks like a permission issue with the test key files; indeed unrelated to this PR. I checked that last merged PR, but I don't see a trace of the AppVeyor test anymore, so can't compare. AppVeyor still uses cygwin in this project (vs. msBuild in openssl); probably time for a revamp.

**Comment by dstebila** [comment]
Are we okay to merge without the AppVeyor builds passing?

**Comment by baentsch** [comment]
> Are we okay to merge without the AppVeyor builds passing?

No need to repeat myself.

> probably time for a revamp.

Yes. If we don't have time for this, my preference would be to remove (documented) Windows support (and AppVeyor along with it) -- possibly creating a new issue to re-enable it at some future time when someone considers this platform relevant again.

**Comment by christianpaquin** [comment]
> Are we okay to merge without the AppVeyor builds passing?

I'm ok too.

**Comment by dstebila** [comment]
> Looks like a permission issue with the test key files; indeed unrelated to this PR. I checked that last merged PR, but I don't see a trace of the AppVeyor test anymore, so can't compare. AppVeyor still uses cygwin in this project (vs. msBuild in openssl); probably time for a revamp.

@christianpaquin Here's the AppVeyor log from commit 92c59cf which was the last commit merged into our main branch OQS-v8.

[log.txt](https://github.com/open-quantum-safe/openssh/files/11040878/log.txt)

**Comment by dstebila** [comment]
> > Are we okay to merge without the AppVeyor builds passing?
> 
> No need to repeat myself.
> 
> > probably time for a revamp.
> 
> Yes. If we don't have time for this, my preference would be to remove (documented) Windows support (and AppVeyor along with it) -- possibly creating a new issue to re-enable it at some future time when someone considers this platform relevant again.

Yes, you're right, we should do this cleanly.

I spent a few minutes looking at the AppVeyor test configuration but can't see anything obvious causing the permissions error nor how to obviously fix it.

I'm not going to be able to investigate further for several weeks, so unless someone else can, we either leave this open or we remove the AppVeyor tests and add an issue tracking that.

**Comment by christianpaquin** [comment]
> @christianpaquin Here's the AppVeyor log from commit [92c59cf](https://github.com/open-quantum-safe/openssh/commit/92c59cf2f25fb32b21ce8d7b11a8af246ea17062) which was the last commit merged into our main branch OQS-v8.
> 
> [log.txt](https://github.com/open-quantum-safe/openssh/files/11040878/log.txt)

I've run a quick diff between the old log and the [new one](https://ci.appveyor.com/api/buildjobs/k0p6d5niwafafi9n/log), and there are some tool versioning differences; perhaps that accounts for the strange behaviour. Regardless, I'm ok with disabling the AppVeyor test and add Windows testing later.

**Comment by christianpaquin** [comment]
We can merge this first, and then update libssh (see [discussion here](https://github.com/open-quantum-safe/libssh/issues/18#issuecomment-1487502973)). Can you rebase on top of #140 to fix the failing CI?

**Review by christianpaquin — APPROVED** [review]
Thanks Panos

**Pull request merged**
